//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 19.03.2016 18:05:11
namespace TeapotSample
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Textures
            {
                
                /// <summary> Path to Content/Assets/Textures/metal_diffuse.png </summary>
                public const string metal_diffuse_png = "Content/Assets/Textures/metal_diffuse.png";
                
                /// <summary> Path to Content/Assets/Textures/metal_normal.png </summary>
                public const string metal_normal_png = "Content/Assets/Textures/metal_normal.png";
            }
            
            public sealed class Materials
            {
                
                /// <summary> Path to Content/Assets/Materials/MetalMaterial.wmat </summary>
                public const string MetalMaterial = "Content/Assets/Materials/MetalMaterial.wmat";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
